# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Download secure file
# Download a secure file to the agent machine
- task: DownloadSecureFile@1
  name: mvnsettings
  inputs:
    secureFile: settings.xml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(mvnsettings.secureFilePath)" "${HOME}/.m2/settings.xml"
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'dev-sonarqube'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'target/classes'
    codeCoverageSourceDirectories: 'src/main/java'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'